/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hackercraft.duals;

import java.lang.System.Logger;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

import kr.entree.spigradle.annotations.SpigotPlugin;
/**
 * Main spigot class Handels all the Registering of plugin
 */
@SpigotPlugin
public class Duals extends JavaPlugin{
    
    private static String prefix = "[Duals]";
    public Logger logger = (Logger) Bukkit.getLogger();



    @Override
    public void onLoad() {
        
    }

    @Override
    public void onEnable() {
      
    }

    @Override
    public void onDisable() {
      
    }

}
